In [54]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [55]:
a[1]

tensor(1.)

In [56]:
float(a[1])


1.0

In [57]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [58]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [59]:
points.shape

torch.Size([3, 2])

In [60]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]
points[1:]
points[1:,:]
points[1:,0]
points.unsqueeze(1)

tensor([[[4., 1.]],

        [[5., 3.]],

        [[2., 1.]]])

In [61]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])
batch_t=torch.randn(2,3,5,5)

In [62]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape

torch.Size([5, 5])

In [63]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze(-1)
img_weights=(img_t*unsqueezed_weights)
barch_weights=(batch_t*unsqueezed_weights)
umg_gray_weighted=img_weights.sum(-3)
barch_gray_weighted=barch_weights.sum(-3)
barch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [64]:
weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [65]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img named:",img_named.shape,img_named.names)
print("batch named:",batch_named.shape,batch_named.names)


img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [66]:
weights_aligned=weights_named.align_as(img_named)
weights_aligned.shape,weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [67]:
gray_named=(img_named*weights_aligned).sum('channels')
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [68]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([1,2])
a+b

tensor([[2, 4],
        [4, 6]])

In [69]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage

<bound method Tensor.storage of tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])>

In [70]:
points_storage = points.storage()
points_storage[0]

4.0

In [71]:
points.storage()[1]

1.0

In [72]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point.storage_offset())


2


In [74]:
second_point

tensor([5., 3.])

In [75]:
def get_points_stride():
    """
    返回点张量的步长。

    张量的步长表示在遍历张量时在每个维度上前进的元素数量。
    它是一个元组，指示在每个维度上跳过的元素数量以移动到下一个元素。

    返回值:
    - stride (tuple): 点张量的步长。
    """
    return points.stride()
points.stride()

(2, 1)

In [76]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [77]:
second_point.storage_offset()

2

In [78]:
second_point.shape

torch.Size([2])

In [79]:
second_point.stride()

(1,)

In [80]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [81]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [89]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
print(points)
print(points_t)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 5., 2.],
        [1., 3., 1.]])


In [90]:
print(id(points.storage()) == id(points_t.storage()))
print(points.stride(), points_t.stride())

False
(2, 1) (1, 2)


In [93]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [102]:

some_t = torch.arange(1, 61).reshape(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
# 使用transpose方法对some_t进行转置操作
transpose_t = some_t.transpose(0, 2)

# 打印转置后的张量形状
print(transpose_t.shape)

torch.Size([5, 4, 3])


In [96]:
transpose_t.shape


torch.Size([5, 4, 3])

In [104]:
some_t.stride()


(20, 5, 1)