In [16]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [17]:
a[1]

tensor(1.)

In [18]:
float(a[1])


1.0

In [19]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [20]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape

torch.Size([3, 2])

In [22]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]
points[1:]
points[1:,:]
points[1:,0]
points.unsqueeze(1)

tensor([[[4., 1.]],

        [[5., 3.]],

        [[2., 1.]]])

In [23]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])
batch_t=torch.randn(2,3,5,5)

In [24]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape

torch.Size([5, 5])

In [25]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze(-1)
img_weights=(img_t*unsqueezed_weights)
barch_weights=(batch_t*unsqueezed_weights)
umg_gray_weighted=img_weights.sum(-3)
barch_gray_weighted=barch_weights.sum(-3)
barch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [27]:
weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [29]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img named:",img_named.shape,img_named.names)
print("batch named:",batch_named.shape,batch_named.names)


img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [30]:
weights_aligned=weights_named.align_as(img_named)
weights_aligned.shape,weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [31]:
gray_named=(img_named*weights_aligned).sum('channels')
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [32]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([1,2])
a+b

tensor([[2, 4],
        [4, 6]])

gray_named=(img_named[..., :3])