In [2]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])


1.0

In [5]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [6]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [7]:
points.shape

torch.Size([3, 2])

In [8]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]
points[1:]
points[1:,:]
points[1:,0]
points.unsqueeze(1)

tensor([[[4., 1.]],

        [[5., 3.]],

        [[2., 1.]]])

In [9]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])
batch_t=torch.randn(2,3,5,5)

In [10]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape

torch.Size([5, 5])

In [11]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze(-1)
img_weights=(img_t*unsqueezed_weights)
barch_weights=(batch_t*unsqueezed_weights)
umg_gray_weighted=img_weights.sum(-3)
barch_gray_weighted=barch_weights.sum(-3)
barch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [12]:
weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

/tmp/ipykernel_2445549/1712500497.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1712608885084/work/c10/core/TensorImpl.h:1921.)
  weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [13]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img named:",img_named.shape,img_named.names)
print("batch named:",batch_named.shape,batch_named.names)


img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [14]:
weights_aligned=weights_named.align_as(img_named)
weights_aligned.shape,weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [15]:
gray_named=(img_named*weights_aligned).sum('channels')
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [16]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([1,2])
a+b

tensor([[2, 4],
        [4, 6]])

In [17]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage

<bound method Tensor.storage of tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])>

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

In [20]:
points.storage()[1]

1.0

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [35]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point.storage_offset())


2


In [30]:
second_point

tensor([4., 5., 2.])

In [32]:
def get_points_stride():
    """
    返回点张量的步长。

    张量的步长表示在遍历张量时在每个维度上前进的元素数量。
    它是一个元组，指示在每个维度上跳过的元素数量以移动到下一个元素。

    返回值:
    - stride (tuple): 点张量的步长。
    """
    return points.stride()
points.stride()

(2, 1)

In [33]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [34]:
second_point.storage_offset()

2

In [36]:
second_point.shape

torch.Size([2])

In [37]:
second_point.stride()

(1,)

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [39]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [40]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [41]:
def transpose_points(points):
    """
    Transposes the given points tensor.

    Args:
        points (Tensor): The input tensor of shape (N, D), where N is the number of points and D is the number of dimensions.

    Returns:
        Tensor: The transposed tensor of shape (D, N).
    """
    points_t = points.t()
    return points_t

points_t = transpose_points(points)

points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
def compare_storage_addresses(points, points_t):
    """
    Compare the storage addresses of two tensors.

    Parameters:
    - points (torch.Tensor): The first tensor to compare.
    - points_t (torch.Tensor): The second tensor to compare.

    Returns:
    - bool: True if the storage addresses are the same, False otherwise.
    """
    return id(points.storage()) == id(points_t.storage())
id(points.storage()) == id(points_t.storage())

False