In [1]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, precision=2, linewidth=75)

set_printoptions函数
函数接受多个参数，包括precision（浮点数输出的精度）、threshold（触发摘要而不是完整repr的数组元素总数）、edgeitems（每个维度开头和结尾的摘要中的数组项数）、linewidth（用于插入换行符的每行字符数）和profile（用于设置预定义的打印选项配置）。

In [2]:
import csv
wine_path = "../data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

fname：要读取的文件名或文件对象。
dtype：返回数组的数据类型，默认为float。
comments：用于指示注释开始的字符或字符列表，默认为'#'。
delimiter：用于分隔值的字符，默认为空格。
converters：用于自定义值解析的转换器函数的字典或可调用对象，默认为None。
skiprows：要跳过的行数，默认为0。
usecols：要读取的列索引或列索引的序列，默认为None，表示读取所有列。
unpack：如果为True，返回的数组将被转置，可以使用x, y, z = loadtxt(...)进行解包，默认为False。
ndmin：返回的数组至少具有的维度数，默认为0，表示返回一维数组。
encoding：用于解码输入文件的编码方式，默认为'bytes'。
max_rows：在跳过行数后读取的最大行数，默认为读取所有行。

In [3]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wineq_numpy.shape, col_list


((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [ ]:
# 打开CSV文件并读取所有行到列表中
with open(wine_path, 'r') as file:
    csv_reader = csv.reader(file)
    rows_list = [row for row in csv_reader]

# 输出结果以验证
print(rows_list)

In [6]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [7]:
data = wineq[:, :-1] # <1>
data, data.shape

(tensor([[ 7.00,  0.27,  ...,  0.45,  8.80],
         [ 6.30,  0.30,  ...,  0.49,  9.50],
         ...,
         [ 5.50,  0.29,  ...,  0.38, 12.80],
         [ 6.00,  0.21,  ...,  0.32, 11.80]]),
 torch.Size([4898, 11]))

In [8]:
target = wineq[:, -1] # <2>
target, target.shape

(tensor([6., 6.,  ..., 7., 6.]), torch.Size([4898]))

In [11]:
target = wineq[:, -1].long()
target, target.shape

(tensor([6, 6,  ..., 7, 6]), torch.Size([4898]))

In [13]:
target_onehot = torch.zeros(target.shape[0], 10)
print(target_onehot.shape)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
target_onehot

torch.Size([4898, 10])


tensor([[0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.],
        ...,
        [0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.]])